### ISSUE TITLE
Linux version doesn't work

### ISSUE THREAD

**Issue by WindowsHandle** [ChengT-cmd/PDG-Debugger#1]
It even can not be compile with g++!
Why!

SYSTEM  :  Kali Linux IV
TIME        :  2020/12/25 21:24 94"124"'
So...

**Comment by ChengT-cmd** [comment]
Because we are developing Linux version -- it not complete.
Please wait until we give you a release version.

**Comment by WindowsHandle** [comment]
Oh.Thanks.

**Comment by ChengT-cmd** [comment]
[If you are not sure,please check on this website to verify if you really want to upload this issue.](http://www.catb.org/~esr/faqs/smart-questions.html)

**Comment by ChengT-cmd** [comment]
AutoValidation: The Issue ends. Thank you to all concerned for their participation.

**Comment by ChengT-cmd** [comment]
AutoValidation: The Issue ends. Thank you to all concerned for their participation.
